### PR TITLE
# Add auto validation config & give a validation sample controller

### PR DESCRIPTION
**Pull request by nets7snipper**

### CODE REVIEW

**Comment by nets7snipper** [comment]
[TestCase](https://q240iu43yr.feishu.cn/docx/M4SgdfqtToV90cxcKxYcqDLFnkr)

**Comment by sol-wizard** [comment]
LGTM, i can see you have a example controller and  DTO, can i know why having the sample? rather having sample can we apply validation in the current API? 

If there is no post endpoint then make sense to leave the sample controller

**Comment by nets7snipper** [comment]
I explained it ON pr review channel.

Aug-8 ***@***.***>于2024年9月13日 周五10:24写道：

**Comment by nets7snipper** [comment]
To refactor task controller contains a lot of work, I just want to make it
simple and give its owner to do it, which may help him know more about our
layered architecture and doing validation

Aug-8 ***@***.***> 于2024年9月13日周五 10:24写道：

**Review by sol-wizard — APPROVED** [review]

**Pull request merged**
